stages:
  - test
  - build_and_push

services:
  - docker:dind

tests:
  image: docker/compose:latest
  stage: test
  script:
    - docker-compose -f docker-compose-ci.yml up -d db
    - docker-compose -f docker-compose-ci.yml up app_test
    - docker-compose -f docker-compose-ci.yml down

build_and_push:
  image: docker/compose:latest
  stage: build_and_push
  variables:
    TAG: $CI_COMMIT_SHA
  script:
    - docker-compose build
    - docker login -u $DOCKER_REGISTRY_LOGIN -p $DOCKER_REGISTRY_PASSWORD
    - docker-compose push
  only:
    - development
    - master
