stages:
  - test

tests:
  image: docker/compose:latest
  stage: test
  script:
    - sudo docker-compose -f docker-compose-ci.yml up -d db
    - sudo docker-compose -f docker-compose-ci.yml app_migration
    - sudo docker-compose -f docker-compose-ci.yml app_test
