version: "3.8"

services:
  db:
    container_name: apple_db
    restart: always
    image: postgres:11
    env_file:
      - .env
    volumes:
    - /app/postgres:/var/lib/postgresql/data

  app_migration:
    image: applehostel/main_app:${TAG}
    restart: on-failure
    container_name: apple_db_migration
    #TODO Изменить на UWSGI внутри докер файла
    command: python manage.py migrate
    depends_on:
      - db
    env_file:
      - .env

  web:
    image: applehostel/main_app:${TAG}
    build: .
    restart: always
    container_name: apple_app
    #TODO Изменить на UWSGI внутри докер файла
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "80:8000"
    depends_on:
      - db
      - app_migration
    env_file:
      - .env