version: "3.8"

services:
  db:
    container_name: apple_db
    restart: always
    image: postgres:11
    env_file:
      - .env.test

  redis_db:
    container_name: redis
    image: redis:6.0.9
    restart: always

  app_test:
    image: applehostel/main_app:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.acceptance_tests
      args:
        REQUIREMENTS_FILE: test
    env_file:
      - .env.test
    container_name: apple_test
    depends_on:
      - db
      - redis_db