version: "3.8"

services:
  db:
    container_name: apple_db
    restart: always
    image: postgres:11
    env_file:
      - .env.test
  app_migration:
    build: .
    env_file:
      - .env.test
    restart: on-failure
    container_name: apple_db_migration
    #TODO Изменить на UWSGI внутри докер файла
    command: python manage.py migrate

    depends_on:
      - db

  app_test:
    build:
      context: .
      args:
        REQUIREMENTS_FILE: local
    env_file:
      - .env.test
    container_name: apple_test
    #TODO Изменить на UWSGI внутри докер файла
    command: python manage.py test
    ports:
      - "80:8000"
    depends_on:
      - db
      - app_migration

