version: "3.3"

services:
  db:
    container_name: apple_db
    restart: always
    image: postgres:11
    env_file:
      - .env
    volumes:
    - /app/postgres:/var/lib/postgresql/data

  app_migration:
    image: applehostel/main_app:${TAG}
    restart: on-failure
    container_name: apple_db_migration
    command: python manage.py migrate
    depends_on:
      - db
    env_file:
      - .env

  redis_db:
    container_name: redis
    image: redis:6.0.9
    restart: always
    env_file:
      - .env

  web:
    image: applehostel/main_app:${TAG}
    build: .
    restart: always
    container_name: apple_app
    command: uwsgi --http :8000 --module main.wsgi
    volumes:
    -  /home/deployciuser/uploads:/uploads
    -  /home/deployciuser/static:/code/main/settings/static
    depends_on:
      - db
      - app_migration
    env_file:
      - .env

  nginx_proxy:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/deployciuser/configs/dhparam.pem:/etc/nginx/conf.d/configs/dhparam.pem
      - /home/deployciuser/configs/self-signed.conf:/etc/nginx/conf.d/configs/self-signed.conf
      - /home/deployciuser/configs/ssl-params.conf:/etc/nginx/conf.d/configs/ssl-params.conf
      - /etc/ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - /etc/ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    depends_on:
      - db
      - app_migration
      - web
