FROM python:3.7
ENV PYTHONUNBUFFERED=1
ARG REQUIREMENTS_FILE="base"
WORKDIR /code
COPY requirements /code
RUN pip install -r /code/$REQUIREMENTS_FILE.txt
RUN apt-get update && apt-get install -y \
    libgbm1 \
    fonts-liberation \
    libappindicator3-1 \
    libasound2 \
    libatk-bridge2.0-0 \
    libnspr4 \
    libnss3 \
    lsb-release \
    xdg-utils\
    libxss1 \
    libdbus-glib-1-2 \
    curl \
    unzip \
    wget \
    xvfb

RUN CHROME_SETUP=google-chrome.deb && \
    wget -O $CHROME_SETUP "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb" && \
    dpkg -i $CHROME_SETUP && \
    apt-get install -y -f && \
    rm $CHROME_SETUP
COPY source /code
EXPOSE 8000