version: "3.8"

services:
  db:
    container_name: apple_db
    restart: always
    image: postgres:11
    env_file:
      - .env.test

  app_test:
    build:
      context: .
      args:
        REQUIREMENTS_FILE: test
    env_file:
      - .env.test
    container_name: apple_test
    ports:
      - "80:8000"
    depends_on:
      - db


