# Generated by Django 2.2.13 on 2020-11-10 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcomeguests', '0002_auto_20201105_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='welcomeguest',
            options={'permissions': [('can_add_welcomeguest', 'Может добавлять желанного гостя'), ('can_change_welcomeguest', 'Может изменять желанного гостя'), ('can_delete_welcomeguest', 'Может удалять желанного гостя'), ('can_view_welcomeguest', 'Может просматривать желанного гостя')], 'verbose_name': 'Желанный гость', 'verbose_name_plural': 'Желанные гости'},
        ),
    ]
