# Generated by Django 2.2.13 on 2020-11-17 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welcomeguests', '0003_auto_20201110_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcomeguest',
            name='guest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hostelguests.Guest', verbose_name='Гость'),
        ),
    ]
