# Generated by Django 2.2.13 on 2020-11-10 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_add_user', 'Может добавлять пользователя'), ('can_change_user', 'Может изменять пользователя'), ('can_delete_user', 'Может удалять пользователя'), ('can_view_user', 'Может просматривать пользователя')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
