# Generated by Django 2.2.13 on 2020-11-05 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostelguests', '0002_auto_20201105_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('note', models.TextField(default='', verbose_name='Заметки о госте')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='hostelguests.Guest', verbose_name='Гость')),
            ],
            options={
                'verbose_name': 'Заметка о госте',
                'verbose_name_plural': 'Заметки о госте',
            },
        ),
    ]
