# Generated by Django 2.2.13 on 2020-11-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutguests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'permissions': [('can_add_note', 'Может добавлять заметку о госте'), ('can_change_note', 'Может изменять заметку о госте'), ('can_delete_note', 'Может удалять заметку о госте'), ('can_view_note', 'Может просматривать заметку о госте')], 'verbose_name': 'Заметка о госте', 'verbose_name_plural': 'Заметки о госте'},
        ),
        migrations.RemoveField(
            model_name='note',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
