# Generated by Django 2.2.13 on 2020-11-11 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutguests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'permissions': [('can_add_note', 'Может добавлять заметку о госте'), ('can_change_note', 'Может изменять заметку о госте'), ('can_delete_note', 'Может удалять заметку о госте'), ('can_view_note', 'Может просматривать заметку о госте')], 'verbose_name': 'Заметка о госте', 'verbose_name_plural': 'Заметки о госте'},
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note',
            new_name='description',
        ),
    ]
