# Generated by Django 2.2.13 on 2020-12-18 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productincomes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productincomes',
            options={'permissions': [('can_add_product_incomes', 'Может оприходовать товар'), ('can_change_product_incomes', 'Может изменять приход товара'), ('can_delete_product_incomes', 'Может удалять приход товара'), ('can_view_product_incomes', 'Может просматривать приход товара')], 'verbose_name': 'Приход товара', 'verbose_name_plural': 'Приходы товара'},
        ),
    ]
