# Generated by Django 2.2.13 on 2020-12-25 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceexecutors', '0005_auto_20201210_1916'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productincomes', '0002_auto_20201218_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productincomes',
            options={'permissions': [('can_add_product_incomes', 'Может создавать приход товара'), ('can_change_product_incomes', 'Может изменять приход товара'), ('can_delete_product_incomes', 'Может удалять приход товара'), ('can_view_product_incomes', 'Может просматривать приход товара')], 'verbose_name': 'Приход товара', 'verbose_name_plural': 'Приходы товара'},
        ),
        migrations.RemoveField(
            model_name='productincomes',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productincomes',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='productincomes',
            name='services_executor',
        ),
        migrations.RemoveField(
            model_name='productincomes',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='Incomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('services_executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceexecutors.ServiceExecutor', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Приход',
                'verbose_name_plural': 'Приходы',
                'permissions': [('can_add_incomes', 'Может создавать приход'), ('can_change_incomes', 'Может изменять приход'), ('can_delete_incomes', 'Может удалять приход'), ('can_view_incomes', 'Может просматривать приход')],
            },
        ),
        migrations.AddField(
            model_name='productincomes',
            name='incomes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_incomes', to='productincomes.Incomes', verbose_name='Приход товара'),
            preserve_default=False,
        ),
    ]
