# Generated by Django 2.2.13 on 2020-11-10 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostelservice',
            options={'permissions': [('can_add_hostelservice', 'Может добавлять услугу отеля'), ('can_change_hostelservice', 'Может изменять услугу отеля'), ('can_delete_hostelservice', 'Может удалять услугу отеля'), ('can_view_hostelservice', 'Может просматривать услугу отеля')], 'verbose_name': 'Услуга отеля', 'verbose_name_plural': 'Услуги отеля'},
        ),
    ]
