# Generated by Django 2.2.13 on 2020-12-03 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostelservices', '0003_auto_20201202_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseprice',
            name='hostel_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_price', to='hostelservices.HostelService', verbose_name='Услуга отеля'),
        ),
        migrations.AddField(
            model_name='sellingprice',
            name='hostel_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selling_price', to='hostelservices.HostelService', verbose_name='Услуга отеля'),
        ),
    ]
