# Generated by Django 2.2.13 on 2020-12-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelservices', '0004_auto_20201203_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseprice',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Цена покупки'),
        ),
    ]
