# Generated by Django 2.2.13 on 2020-12-18 10:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostelguests', '0004_auto_20201202_2044'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20201218_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('qty', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена закупки')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена продажи')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostelguests.Guest', verbose_name='Гость')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Запись продажи',
                'verbose_name_plural': 'Записи продаж',
                'permissions': [('can_add_sellinghistory', 'Может добавлять запись продажи'), ('can_change_sellinghistory', 'Может изменять запись продажи'), ('can_delete_sellinghistory', 'Может удалять запись продажи'), ('can_view_sellinghistory', 'Может просматривать запись продажи')],
            },
        ),
    ]
