# Generated by Django 2.2.13 on 2020-11-10 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unwelcomeguests', '0002_auto_20201105_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unwelcomeguest',
            options={'permissions': [('can_add_unwelcomeguest', 'Может добавлять нежеланного гостя'), ('can_change_unwelcomeguest', 'Может изменять нежеланного гостя'), ('can_delete_unwelcomeguest', 'Может удалять нежеланного гостя'), ('can_view_unwelcomeguest', 'Может просматривать нежеланного гостя')], 'verbose_name': 'Нежеланный гость', 'verbose_name_plural': 'Нежеланные гости'},
        ),
    ]
