# Generated by Django 2.2.13 on 2020-12-17 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название продукта')),
                ('qty', models.IntegerField(default=0, verbose_name='Колличество')),
                ('barcode', models.IntegerField(null=True, verbose_name='Штрих код')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Цена продажи')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Цена продажи')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'permissions': [('can_add_product', 'Может добавлять продукт'), ('can_change_product', 'Может изменять продукт'), ('can_delete_product', 'Может удалять продукт'), ('can_view_product', 'Может просматривать продукт')],
            },
        ),
    ]
