# Generated by Django 2.2.13 on 2020-12-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201219_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
    ]
