# Generated by Django 2.2.13 on 2020-12-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201219_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Штрих код'),
        ),
    ]
