# Generated by Django 2.2.13 on 2021-01-05 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Отчество')),
                ('passport_id', models.CharField(max_length=255, verbose_name='Номер паспорта')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('relative_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона родственника')),
                ('labor_contract', models.FileField(blank=True, null=True, upload_to='labor_contracts', verbose_name='Трудовой договор')),
                ('passport', models.ImageField(blank=True, null=True, upload_to='passport_photos', verbose_name='Копия паспорта')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos', verbose_name='Фото сотрудника')),
                ('achievement', models.TextField(blank=True, default='', max_length=255, verbose_name='Достижения')),
                ('deposit_amount', models.IntegerField(blank=True, default='', verbose_name='Сумма депозита')),
                ('medical_record', models.BooleanField(default=True)),
                ('address', models.TextField(default='', verbose_name='Адрес')),
                ('note', models.TextField(default='', verbose_name='Примечание')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
