# Generated by Django 2.2.13 on 2021-01-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('can_add_employee', 'Может добавлять сотрудника'), ('can_change_employee', 'Может изменять сотрудника'), ('can_delete_employee', 'Может удалять сотрудника'), ('can_view_employee', 'Может просматривать сотрудника')], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='medical_record',
            field=models.BooleanField(default=False),
        ),
    ]
