# Generated by Django 2.2.13 on 2021-01-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20210107_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Примечание'),
        ),
    ]
