# Generated by Django 2.2.13 on 2021-01-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20210110_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='deposit_amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сумма депозита'),
        ),
    ]
