# Generated by Django 2.2.13 on 2021-01-17 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20210110_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='deposit_amount',
        ),
    ]
