# Generated by Django 2.2.13 on 2021-01-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_employee_deposit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='deposit_amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сумма депозита'),
        ),
    ]
