# Generated by Django 2.2.13 on 2020-11-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceexecutors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceexecutor',
            options={'permissions': [('can_add_serviceexecutor', 'Может добавлять исполнителя'), ('can_change_serviceexecutor', 'Может изменять исполнителя'), ('can_delete_serviceexecutor', 'Может удалять исполнителя'), ('can_view_serviceexecutor', 'Может просматривать исполнителя')], 'verbose_name': 'Исполнитель', 'verbose_name_plural': 'Исполнители'},
        ),
    ]
