# Generated by Django 2.2.13 on 2020-11-24 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceexecutors', '0002_auto_20201110_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceexecutor',
            name='document',
        ),
    ]
