# Generated by Django 2.2.13 on 2020-12-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceexecutors', '0004_serviceexecutor_hostel_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceexecutor',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Отчество'),
        ),
    ]
