# Generated by Django 2.2.13 on 2020-12-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceexecutors', '0005_auto_20201210_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceexecutor',
            name='payment',
            field=models.CharField(choices=[('cash', 'Наличный'), ('non-cash', 'Безналичный')], default='cash', max_length=20, verbose_name='Тип оплаты'),
        ),
        migrations.AddField(
            model_name='serviceexecutor',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона'),
        ),
    ]
