# Generated by Django 2.2.13 on 2020-11-26 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceexecutors', '0003_remove_serviceexecutor_document'),
        ('documents', '0004_auto_20201111_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='service_executor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='serviceexecutors.ServiceExecutor', verbose_name='Исполнитель'),
        ),
    ]
