# Generated by Django 2.2.13 on 2020-11-30 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_service_executor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
    ]
