# Generated by Django 2.2.13 on 2020-11-08 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serviceexecutors', '__first__'),
        ('hostelguests', '0002_auto_20201105_0920'),
        ('hostelservices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('executor', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='serviceexecutors.ServiceExecutor', verbose_name='Исполнитель')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelguests.Guest', verbose_name='Гость')),
                ('hostel_service', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='hostelservices.HostelService', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Журнал услуг',
                'verbose_name_plural': 'Журналы услуг',
            },
        ),
    ]
