# Generated by Django 2.2.13 on 2020-11-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceexecutors', '0001_initial'),
        ('hostelguests', '0002_auto_20201105_0920'),
        ('hostelservices', '0001_initial'),
        ('journalservices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalservice',
            name='executor',
        ),
        migrations.AddField(
            model_name='journalservice',
            name='executor',
            field=models.ManyToManyField(to='serviceexecutors.ServiceExecutor', verbose_name='Исполнитель'),
        ),
        migrations.RemoveField(
            model_name='journalservice',
            name='guest',
        ),
        migrations.AddField(
            model_name='journalservice',
            name='guest',
            field=models.ManyToManyField(to='hostelguests.Guest', verbose_name='Гость'),
        ),
        migrations.RemoveField(
            model_name='journalservice',
            name='hostel_service',
        ),
        migrations.AddField(
            model_name='journalservice',
            name='hostel_service',
            field=models.ManyToManyField(to='hostelservices.HostelService', verbose_name='Услуга'),
        ),
    ]
