# Generated by Django 2.2.13 on 2020-11-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalservices', '0002_auto_20201108_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalservice',
            options={'permissions': [('can_add_journalservice', 'Может добавлять журнал услуг'), ('can_change_journalservice', 'Может изменять журнал услуг'), ('can_delete_journalservice', 'Может удалять журнал услуг'), ('can_view_journalservice', 'Может просматривать журнал услуг')], 'verbose_name': 'Журнал услуг', 'verbose_name_plural': 'Журналы услуг'},
        ),
    ]
