# Generated by Django 2.2.13 on 2020-11-17 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceexecutors', '0002_auto_20201110_1750'),
        ('hostelguests', '0003_auto_20201113_2305'),
        ('hostelservices', '0002_auto_20201110_1746'),
        ('journalservices', '0003_auto_20201110_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalservice',
            name='executor',
        ),
        migrations.AddField(
            model_name='journalservice',
            name='executor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='serviceexecutors.ServiceExecutor', verbose_name='Исполнитель'),
        ),
        migrations.RemoveField(
            model_name='journalservice',
            name='guest',
        ),
        migrations.AddField(
            model_name='journalservice',
            name='guest',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='hostelguests.Guest', verbose_name='Гость'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='journalservice',
            name='hostel_service',
        ),
        migrations.AddField(
            model_name='journalservice',
            name='hostel_service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='hostelservices.HostelService', verbose_name='Услуга'),
        ),
    ]
