# Generated by Django 2.2.13 on 2020-12-02 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostelservices', '0003_auto_20201202_1713'),
        ('journalservices', '0005_auto_20201119_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalservice',
            old_name='executor',
            new_name='service_executor',
        ),
        migrations.AddField(
            model_name='journalservice',
            name='purchase_price',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='hostelservices.PurchasePrice', verbose_name='Цена покупки'),
        ),
        migrations.AddField(
            model_name='journalservice',
            name='selling_price',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='hostelservices.SellingPrice', verbose_name='Цена продажи'),
        ),
    ]
