# Generated by Django 2.2.13 on 2020-11-04 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(default='', max_length=255, verbose_name='Отчество')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='guest_photos', verbose_name='Аватара')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('birth_country', models.CharField(max_length=255, verbose_name='Страна рождения')),
                ('passport_id', models.CharField(max_length=255, verbose_name='Номер паспорта')),
                ('expiry_passport_date', models.DateField(null=True, verbose_name='Дата окончания срока действия')),
                ('document_maker', models.CharField(max_length=255, null=True, verbose_name='Страна рождения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
            },
        ),
    ]
