# Generated by Django 2.2.13 on 2020-11-05 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostelguests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='user',
        ),
        migrations.AddField(
            model_name='guest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='document_maker',
            field=models.CharField(default='', max_length=255, verbose_name='Орган выдавший документ'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='guest_photos', verbose_name='Фото'),
        ),
    ]
