# Generated by Django 2.2.13 on 2020-11-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelguests', '0002_auto_20201105_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'permissions': [('can_add_guest', 'Может добавлять гостя'), ('can_change_guest', 'Может изменять гостя'), ('can_delete_guest', 'Может удалять гостя'), ('can_view_guest', 'Может просматривать гостя')], 'verbose_name': 'Гость', 'verbose_name_plural': 'Гости'},
        ),
        migrations.AlterField(
            model_name='guest',
            name='document_maker',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Орган выдавший документ'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='expiry_passport_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания срока действия'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Отчество'),
        ),
    ]
