# Generated by Django 2.2.13 on 2020-12-02 14:44

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hostelguests', '0003_auto_20201113_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='birth_country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
