# Generated by Django 2.2.13 on 2021-01-06 12:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('hostelguests', '0004_auto_20201202_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='guest',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None, verbose_name='Контактный номер телефона'),
        ),
    ]
